### ISSUE TITLE
Change data import

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalr#104]
As part of a move to change where (and how) were do data archiving, we will need to make some changes to where Portalr is grabbing data and how it processes it. The changes below will need to be coordinated with the Issue over on PortalData: (https://github.com/weecology/PortalData/issues/189)

This issue will affect all data (not just the rodents).
- [ ] Issue #106 : Portalr will need to import data from the new Zenodo archive (when it is created: https://github.com/weecology/PortalData/issues/188). This will be the official data source for both intra-lab projects and external projects. 

These issues will only apply to the rodents:
- [x] Issue #107 Give portalr the capability to manage out data based on the QA/QC flag

**Comment by gmyenni** [comment]
Getting the latest release from Zenodo is not straightforward, so we're going to default to downloading from the Github master zip for now.

**Comment by ha0ye** [comment]
@gmyenni I don't think it's that bad - we can just scrape the webpage for the download link. At least until Zenodo releases an updated API with access to download files.

**Comment by gmyenni** [comment]
Right, scraping the webpage is what I told Ethan we'd have to do. We decided to download from Github for now, to make the switch to Zenodo a less urgent need (described in #105).

**Comment by gmyenni** [comment]
Closing via #115. Zenodo import issue remains alive in #105.
