### ISSUE TITLE
Filter rodents on QA/QC flag

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalr#107]
When the new QA/QC flag is added to the rodent trapping table (https://github.com/weecology/PortalData/issues/190), we will need to change how portalr manages the rodent data.

- [ ] default to stripping out the data still in the QA/QC period
- [ ] allow an option for users to include the QA/QC data in their rodent data

**Comment by ha0ye** [comment]
Does this replace the current method of asking for "release" versions of the data, and instead put that selection into the data summary functions?

**Comment by skmorgane** [comment]
This particular issue doesn't do that, but is part of a larger string of issues (#104) that will change a) change how we release data and b) where releases will be stored and accessed.

**Comment by ha0ye** [comment]
Looping in @DAPPERstats, since this is related to their recent work on filtering the data by sampling effort.

**Comment by DAPPERstats** [comment]
I would think that filtering should happen within `clean_rodent_data`, where most all of the similar filtering and such of the data occur (e.g. based on `length`), yeah?

**Comment by ha0ye** [comment]
Ah, I think I moved the filter based on `length` out of `clean_rodent_data`, since it became redundant with what you were doing with the trapping table...

**Comment by DAPPERstats** [comment]
I don't think it's redundant, per se, to what's happening in the trapping table. The `length` input forces a hard filter based on plot ID, whereas the trapping table stuff works off of efforts. If the user only wants "longterm" plots, doesn't it make sense to trim the data to the longterm plots as early as possible?

**Comment by ha0ye** [comment]
In that case, maybe where the trapping data gets merged in as part of `make_plot_data` should occur earlier? That might simplify the processing pathway into something like:

1. join all relevant covariates
2. drop unwanted factors
3. summarize by grouping
4. coerce into NAs and 0s
5. reshape and prep output

**Comment by skmorgane** [comment]
Just to be clear, QA/QC in this issue refers to a new flag that will simply indicate which rodent data is still in the data checking phase (because we track individuals, we often have data in this category for a few months to catch any issues with mis-identifying various aspects about the individual). This doesnt have anything to do with sampling effort, which is a separate data issue that @DAPPERstats is handling.

**Comment by ha0ye** [comment]
Adding a note that when this is done, we might want to switch to using the QA/QC'd subset of the data for tests (right now we're pulling down the latest repo version).
