### ISSUE TITLE
Estimate missing trapping data

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#122]
If `fill_incomplete = TRUE`, fill missing data points with estimates using other plots trapped in same census, same plot in previous and subsequent censuses.

Possibly allow options for how to estimate?

**Comment by diazrenata** [comment]
I had a question about the current master portalr version of this function. It looks to me like fill_incomplete is currently not supported? 

`process_incomplete_censuses <- function(rodent_species_merge,
                                       fill_incomplete) {`

 ` if (fill_incomplete) {`

    #incompsampling <- find_incomplete_censuses(rodent_species_merge,trapping_table)

    warning("fill_incomplete not done")
    }

 ` return(rodent_species_merge)`

`}`

It's been a little while since I looked at this, so I want to be sure I'm on the same page as folks who have been more active on this recently - @ha0ye, @DAPPERstats?

**Comment by ha0ye** [comment]
This is new to me, and looks like it has to do with incomplete trapping sessions?
```
#' @param fill_incomplete Logical. Either reports raw data from incomplete trapping sessions
#'   (fill_incomplete = FALSE) or estimates corrected values (fill_incomplete = TRUE)
#'   [note that if level="plot" and fill.incomplete=FALSE, NAs will be included in
#'    periods where trapping was incomplete]
```

The code @diazrenata provided earlier to fill in missing weights seems to be present and working, so I think this may be a different issue?

**Comment by diazrenata** [comment]
You’re right, I’m sorry! I’ve had a kind of disorienting week, and I put
this with the wrong issue.

**Comment by ha0ye** [comment]
I tracked this change down to PR #114, which added in filtering of incomplete censuses using `min_plots` and `min_traps`. There, @gmyenni commented that keeping an `incomplete` argument might be useful for naive users who just want full trapping sessions.

https://github.com/weecology/portalr/pull/114#issuecomment-381809490
> It sounds like what you're suggesting above is that incomplete could be for naive users, who don't really know how many plots or traps they want, but just want complete trapping sessions, while the min_plots and min_traps arguments would be for more advanced users who know what min_plots=24 or even min_plots=24, min_traps=47 actually means.
> 
> We still need part 1.3 of my comment over in #88
> 
> An incomplete argument that has options:
> 1. remove all incomplete sampling
> 2. use all raw abundances
> 3. adjust abundances according to number of plots trapped (#47 )

I think our later discussion on scaling by effort led to having an option to include effort with the output and letting users decide if they want to scale by number of plots or traps. I'm in favor of ditching `fill_incomplete` and instead adding in `incomplete` that sets default values for `min_traps` and `min_plots`.

**Comment by gmyenni** [comment]
`fill_incomplete` does nothing right now, because we haven't made a decision how to do the adjustment (I think what we were leaning toward was to generate estimates for a full trapping session based on the partial numbers, or based on the adjacent sessions, if it was skipped completely. Which is why it's called `fill_incomplete`.) 

Right now it's just a place holder. But it is the argument that should be used to specify whether values should be adjusted for effort or not (default not).

@ha0ye are you saying we should ditch the idea of providing the option to correct for incomplete effort? Or are you saying we should also add back in an `incomplete` argument that just sets `min_plots` and `min_traps`?:

- `incomplete = FALSE`:
  - `min_plots=24` 
  - `min_traps=47` 

- `incomplete = TRUE`:
  - `min_plots=1` 
  - `min_traps=1` 

That is what I was suggesting at one point, but I think we decided against it because `min_plots`/`min_traps` aren't really that difficult to understand on their own.

**Comment by ha0ye** [comment]
I think there are too many options and opinions about interpolating missing data that it's probably not worth our time to try and deal with them all on a package level. Instead, I would prefer to write a vignette that goes through how to do some basic interpolation for incomplete effort and missing censuses -- someone could then copy that code for their use or adapt it accordingly.

I bet @juniperlsimonis has thoughts... :)

**Comment by gmyenni** [comment]
Okay, if we're not going to do this, then (once we hear from all the contributors) we can close this issue and delete `fill_incomplete`. There is already an option to report effort. (And I think we don't need an `incomplete` option, but others can weigh in on that too.)

**Comment by juniperlsimonis** [comment]
i'm in agreement with what you all propose here (deleting `fill_incomplete` and not having an `incomplete` option)
it's better to keep things tidy in the package/function and i like the idea of having a simple vignette to interpolate if folks need it.

**Comment by gmyenni** [comment]
So just to also confirm with those who have expressed a desire for this functionality (I think primarily @diazrenata, but also @emchristensen and @bleds22e ) does this sound good to you all?

**Comment by emchristensen** [comment]
Sure -- just to be clear, we're talking about creating a separate function that does an interpolation or whatever instead of building that in to the data-acquisition function, yes?

**Comment by gmyenni** [comment]
Not exactly. We're talking about providing a vignette that would provide some examples of interpolation or adjusted abundance/effort. You would have to go to the vignette and adapt the examples to get whatever corrected values you want. A separate function would be another (alternative) option, but more complicated, because then we're back to having to make decisions for others exactly how to do the interpolation, etc.

**Comment by diazrenata** [comment]
That makes sense. A new function would need a lot of documentation, so a
vignette might actually provide the same usefulness in a clearer format....

**Comment by emchristensen** [comment]
Ok fine. I suppose it is the kind of thing users shouldn't be doing unless they have a good reason. But I can't promise I won't write a function next time I have to do this... ;)

**Comment by ha0ye** [comment]
@emchristensen Is that a threat or a promise??? :laughing:
