### ISSUE TITLE
Add vignettes to demonstrate usage of the package

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#123]
In prep for a submission to CRAN and JOSS, it would be ideal to have several vignettes with short examples of using the portalr functions to get the Portal data and do some simple analyses or plots.

Here's a suggested workflow for writing a vignette:
1. Make a new Rmarkdown file within the `vignettes` folder.
  * If you're using RStudio, you can select "From Template" -> "Package Vignette (HTML)"
  * You can also try `devtools::use_vignette("<vignette name>")`
2. Follow standard Rmarkdown for writing the vignette.
3. Use `devtools::build_vignettes()` to build and include the vignette files to the package.
4. (standard Git add, commit, push, pull-request)

**Note, if you use packages in the vignette that aren't dependencies of portalr, make sure to include them in the `DESCRIPTION` file under `Suggests:`**

There's an example already in the `vignettes` folder that you can take a look at.

**Comment by gmyenni** [comment]
- Estimating missing data

- Energy

-
