### ISSUE TITLE
Document / Test these Functions

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#129]
Identify what arguments and functions aren't documented, and begin assignment.

| Function Name | File | Documented | Tested | Assigned |
|----------------|-----|--------------|--------|----------|
| colony_presence_absence | ant_data_summaries.R | yes | yes | @emchristensen |
| bait_presence_absence | ant_data_summaries.R | yes | yes | @emchristensen |
| clean_data | data_processing.R | yes | NA (non-exported) | @ha0ye |
| remove_suspect_entries | data_processing.R | yes | NA (non-exported) | @ha0ye |
| process_unknownsp | data_processing.R | yes | yes | @ha0ye |
| process_granivores | data_processing.R | yes | yes | @ha0ye |
| find_incomplete_censuses | data_processing.R | yes | yes | @ha0ye |
| process_incomplete_censuses | data_processing.R | no | -- | @ha0ye |
| filter_plots | data_processing.R | yes | yes | -- |
| join_plots_to_rodents | data_processing.R | yes | NA (non-exported) | @ha0ye |
| join_trapping_to_rodents | data_processing.R | yes | NA (non-exported) | @ha0ye |
| join_plots_to_trapping | data_processing.R | yes | NA (non-exported) | @ha0ye |
| add_time | data_processing.R | yes | NA (non-exported) | @ha0ye |
| make_crosstab | data_processing.R | yes | NA (non-exported) | @ha0ye |
| fill_weight | data_processing.R | yes | yes | @ha0ye |
| clean_rodent_data | data_processing.R | yes | yes | -- |
| rename_species_plants | data_processing.R | yes | NA (non-exported) | @ha0ye |
| process_unknownsp_plants | data_processing.R | yes | NA (non-exported) | @ha0ye |
| process_annuals | data_processing.R | yes | NA (non-exported) | @ha0ye |
| join_census_to_dates | data_processing.R | yes | NA (non-exported) | @ha0ye |
| join_census_to_quadrats | data_processing.R | yes | NA (non-exported) | @ha0ye |
| clean_plant_data | data_processing.R | yes | yes | @ha0ye |
| get_future_moons | get_future_moons.R | yes | yes | @ha0ye |
| FullPath | GetData.R | yes | NA (non-exported) | @ha0ye |
| download_observations | GetData.R | yes | yes | -- |
| check_for_newer_data | GetData.R | yes | yes | -- |
| get_github_releases | GetData.R | yes | NA (non-exported) | -- |
| load_data | GetData.R | yes | yes | -- |
| load_plant_data | GetData.R | yes | yes | @ha0ye |
| load_ant_data | GetData.R | yes | yes | @emchristensen |
| get_stake_data | IndividualData.R | yes | yes | -- |
| make_timeseries | make_monthly_timeseries.R | yes |  | @skmorgane |
| filter_diffs | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| calc_diff | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| shift_current_month | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| shift_next_month | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| shift_current_next | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| fix_period | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| insert_missing_months | make_monthly_timeseries.R | no | NA (non-exported) | @skmorgane |
| ndvi | NDVI.R | yes | yes | -- |
| fill_missing_ndvi | NDVI.R | yes | yes | @DAPPERstats  |
| fcast_ndvi | NDVI.R | yes | yes | @DAPPERstats  |
| get_plant_data | PlantData.R | yes | yes | @emchristensen |
| plant_abundance | PlantData.R | yes| yes | -- |
| true_length | RodentData.R | yes | NA (non-exported) | -- |
| make_plot_data | RodentData.R | yes | NA (non-exported) | -- |
| make_level_data | RodentData.R | yes | NA (non-exported) | @ha0ye |
| prep_rodent_output | RodentData.R | yes | NA (non-exported) | -- |
| get_rodent_data | RodentData.R | yes | yes | @ha0ye |
| abundance | RodentData.R | yes | yes | -- |
| biomass | RodentData.R | yes | yes | -- |
| energy | RodentData.R | yes | yes | -- |
| add_seasons | season_function.R | yes | yes | -- |
| yearly | season_function.R | yes | yes | -- |
| weather | Weather.R | yes | yes | -- |
| fill_missing_weather | Weather.R | yes | NA (non-exported) | @ha0ye  |

**Comment by ha0ye** [comment]
I’ve changed it to snake_case in my edits. :) 🐍

**Comment by DAPPERstats** [comment]
tests for `fill_missing_ndvi` and `fcast_ndvi` added in #148

**Comment by gmyenni** [comment]
I think we can just not export `make_timeseries` for the first release.
We need some more time to think about how it should work to make it generally useful.

**Comment by ha0ye** [comment]
Ok, then I think we can consider this issue resolved and open a new one just for `make_timeseries` if it does not already exist.
