### ISSUE TITLE
Prep for CRAN submission

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#141]
- [x] check off other issues
- [x] add .zenodo.json
- [x] update and check `DESCRIPTION` file
- [x] release 0.1 and submit to CRAN
- [x] add Zenodo link

**Comment by ha0ye** [comment]
I'm not sure who has access to the repo settings, but can one of you point Zenodo to archive portalr on release? @gmyenni or @skmorgane, perhaps?

**Comment by ethanwhite** [comment]
> I'm not sure who has access to the repo settings, but can one of you point Zenodo to archive portalr on release?

Done
