### ISSUE TITLE
Use CRAN template for CRAN submission

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#161]
See https://cran.r-project.org/web/licenses/

**Comment by ethanwhite** [comment]
Licensing properly is definitely a little tricky with CRAN. For [`rdataretriever`](https://github.com/ropensci/rdataretriever) we have both a `LICENSE` file, which is the two liner that CRAN uses, and a `LICENSE.md` file to provide a proper license for the repository. I'm pretty sure we got this from some other `ropensci` projects as the best general solution that doesn't require tweaking code for CRAN submissions.
