### ISSUE TITLE
Add functions or docs to normalize for sampling effort

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#171]
It may not be apparent that some rodent censuses are dropped from the default call to `abundance()` because of `min_plots = 24`. Things we could consider
* add a message that certain time points were dropped
* add some functionality to normalize for effort (maybe too many different options to do in code)
* add a vignette to show how to normalize for effort in some simple ways

**Comment by gmyenni** [comment]
The second option was discussed in #47 and #122. We decided on a vignette. I closed those and listed it as a vignette to add in #123. 

We could also add a message. But it is the default behavior. So a 'warning' might be kind of annoying.
