### ISSUE TITLE
Add pkgdown docs

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#172]
We should probably make a pkgdown site for portalr. Since we already have Travis CI set up to run tests, I think it should be a few lines here and there to get it all working. I believe this would be a good task if anyone wants to learn a bit more about Travis CI, github pages, and/or pkgdown.

I made a quick blogpost that can be used as a guide:
https://haoye.us/post/2018-10-24-pkgdown-ci/

**Comment by gmyenni** [comment]
You mean in DESCRIPTION? I removed the other url, and fixed the link for portaldata.

**Comment by ha0ye** [comment]
Sorry I meant at the top of the GitHub page. We should keep the github URL in DESCRIPTION for CRAN and the pkgdown site to refer back to.

![screen shot 2018-12-12 at 1 48 19 pm](https://user-images.githubusercontent.com/5835366/49891536-c43e0500-fe14-11e8-8d38-a99bf7f49cea.png)

**Comment by gmyenni** [comment]
Ah, okay. That didn't seem right. I'll do that and then close this.

**Comment by gmyenni** [comment]
Why does it look stupid?

**Comment by ha0ye** [comment]
I guess it doesn't support markdown?

Do we need the link to portalData at the top? It is in the readme.

**Comment by gmyenni** [comment]
No. It would just look so nice. 👎 Oh well.
