### ISSUE TITLE
add_seasons function does not give a "season year" column for summarizing

### ISSUE THREAD

**Issue by bleds22e** [weecology/portalr#173]
I think it would probably be a good idea to add an option to the add_seasons function for a "seasonal year" column or something along those lines. Trying to summarize seasonal data by year is complicated because December is in the winter season along with Jan and February. If someone uses the add_seasons function for their own dataframe of Portal data (as I am) and just does group_by(year, season), December is going to be in the wrong year, messing up the summary. Having the option to spit out a seasonal_year column for summary purposes would be helpful (e.g. group_by(seasonal_year, season))

**Comment by emchristensen** [comment]
I've had this problem in the past, and my solution was to add a column called water_year, trying to capture the idea that in this system any rainfall from about October on contributes to the biology of the following spring. So water_year 2019 would start in Fall 2018. Not sure if that's easier or harder to think about conceptually compared to a seasonal_year, just a thought (and it's what I'm doing with the data I'm working on now, they sometimes spread out quadrat sampling October-March and I needed a way to indicate a single "year")

**Comment by bleds22e** [comment]
I also make myself a "season year" column when I start working with the data, but I've never used the add_seasons function from portalr myself, and I realized that most people who try to use it won't know to make the season_year or water_year column

**Comment by ha0ye** [comment]
tasks:
- [ ] add tests to check add_seasons output
- [ ] add functionality to include additional columns

**Comment by gmyenni** [comment]
#238 adds a `seasonyear` column. If you don't specify a summary function, `add_seasons` will return the original data with both `season` and `seasonyear` columns added. For summaries, the function will have already grouped and summarized by `seasonyear`, so it just returns `season` and `year` columns. But `season` is now correctly assigned factor levels (sorting by season is temporal not alphabetical).
