### ISSUE TITLE
JOSS review: Consider renaming/restructuring load_ functions?

### ISSUE THREAD

**Issue by Pakillo** [weecology/portalr#180]
Hi,

Another comment related to my JOSS review (https://github.com/openjournals/joss-reviews/issues/1098).

As my first encounter with the package, I got a bit confused at first with the load_* functions (https://weecology.github.io/portalr/reference/load_data.html). It isn't obvious from their names what particular data these functions are loading. As there is `load_plant_data` and `load_ant_data`, maybe `load_data` could be renamed as `load_rodent_data` for consistency, or `load_trapping_data` to account for the fact that not only rodents fall in traps, but also reptiles, birds, etc?

I note there is already a `load_trapping_data` function, but this one does not seem to load any abundance or catch data like the others, but rather the data on when and where trappings took place? Then this function role would be different from the other three (i.e. loading data from rodents (mostly), plants, and ants), and could be perhaps renamed as an independent function? (e.g. as the others you have to get weather data, NDVI, etc).

Just a suggestion... Because it took me a couple of minutes to learn what each function would do. But up to you of course!

**Comment by ha0ye** [comment]
This partly historical legacy of the package originally being developed around the rodent data, and then adding in the functionality for plant and ant data later.

Ideally, most users shouldn't be using the `load_*` functions at all, but some folks who have built on older versions of the package may rely on `load_data`. The solution is probably some form of:
* add `load_rodent_data` as an alias, and deprecate `load_data`
* add 1 or 2 functions that just load in the metadata tables, to replace some uses of `load_data` (as in the `rodent-abundance-demo` vignette)

**Comment by ha0ye** [comment]
Proposed changes:
* rename `get_***_data()` --> `summarize_***_data()`
* rename `load_data()` --> `load_rodent_data()`
* simplify and export `load_generic_data()` for loading individual table files (e.g. for specific metadata files)

**Comment by ha0ye** [comment]
@diazrenata Did you have thoughts on renaming `get_stake_data()`?

**Comment by diazrenata** [comment]
It seems more intuitive to me to refer to it as `get_individual_data`, but I can see the rationale for `get_stake_data`.

**Comment by ha0ye** [comment]
@diazrenata Well, since we're renaming `get_rodent_data()` to `summarize_rodent_data()`, are you in favor of `summarize_individual_data()`? I was wondering if `summarize_individual_rodents()` would be clearer about it being the rodent data.

**Comment by gmyenni** [comment]
The initial idea was that `stake_data` was the more or less 'raw' individual data, and `individual_data` would be the 'cleaned' individual data (where unique tags actually refer to distinct individuals), which is still on the to-do list. But we could also call this the `individual_data`, and call the cleaned data `tag_data`. That's probably more intuitive all the way around, yeah? ie `summarize_individual_rodents()` and `summarize_rodent_tags()`

**Comment by gmyenni** [comment]
Note though that this function doesn't (at the moment) actually summarize. It just cleans a bit. So while that would be consistent with the 'type' of function it is, it isn't technically true.
