### ISSUE TITLE
Use a system variable to store the default data path

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#185]
The current package assumes a default path of `~` for the data. We could use a system variable to store this location, and enable users to update it, so that they only have to set it once on their system.

**Comment by gavinsimpson** [comment]
This seems a little inflexible if one wants to actively maintain two or more copies of portal data in different projects. Was there a reason to not allow/discourage/not promote the use of a specific path at runtime? From the vignettes it seems that a user-specified path based workflow is allowed, via `load_rodent_data()` for example. Which leaves me wondering why it is necessary to warn the user upon package load that they should set an env var and mess with `.Renviron`?

**Comment by ethanwhite** [comment]
Thanks for all the notes @gavinsimpson! Just stopping in to let you know that it's the Portal spring plant census this week so you probably won't hear back until those folks are back from the field.

Also, can you open a new issue for this. It's been 5 years so I have no recollection of any discussions we had about this at the time, but I do like the idea of specifying data location as the norm and I fell like that's what we frequently do in house at this point. If you can describe your envisioned standard usage in an issue then when folks get back from the field we can chat about potentially changing things, keeping the `~` default, but potentially dropping the warning and updating documentation to focus on specifying paths for both download and use functions.

**Comment by ha0ye** [comment]
I think our thoughts were to try and make the downloading updated versions of the data seamless for most users, so that there _wasn't_ multiple different versions of the data floating around someone's computer.

> This seems a little inflexible if one wants to actively maintain two or more copies of portal data in different projects. 

I can reckon that this would be a useful feature. Maybe the ideal feature is to still keep the single data directory, but store different versions in sub-folders. The default behavior can still be to use the most recent version, but older versions could be saved and accessed by version number.

This would also make the code more transparent to readers, since the version number would be in any scripts, rather than a directory path that is more opaque.

Since there is a bit of back-compatibility concern, said feature would need to check if the data directory isn't currently set up with subfolders for versions and move files accordingly.
