### ISSUE TITLE
upcoming CRAN release of dplyr (Feb 8)

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#192]
* A new version of dplyr is ready to go to CRAN. dplyr is
  currently at version 0.7.8 and will become 0.8.0 upon release.

* portalr uses dplyr and has problems with the new version.

* We plan to submit dplyr to CRAN on February 8.

This release represents about 9 months of development, detailed in
this blog post:
https://www.tidyverse.org/articles/2018/12/dplyr-0-8-0-release-candidate/

Read about the changes to dplyr at
   https://github.com/tidyverse/dplyr/blob/master/NEWS.md#dplyr-080.
   This page includes a list of breaking changes, the reasoning behind
   them, and to how to update your code.

```
== CHECK RESULTS ========================================

*   checking tests ...
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      > library(portalr)
      >
      > test_check("portalr")
      ── 1. Failure: data generated by level = plot, time = newmoon,
type = granivore,
      digest::digest(data) not identical to "22f018525c242edaa3f94814e04d230b".
      1/1 mismatches
      x[1]: "edcd782e39d3a642b3d6273d893f8ed1"
      y[1]: "22f018525c242edaa3f94814e04d230b"

      ══ testthat results
═══════════════════════════════════════════════════════════
      OK: 137 SKIPPED: 14 FAILED: 1
      1. Failure: data generated by level = plot, time = newmoon, type
= granivore, shape = flat is same (@test-99-regression.R#26)

      Error: testthat unit tests failed
      Execution halted
```

**Comment by ha0ye** [comment]
resolved in https://github.com/weecology/portalr/commit/7bb11c5126706e8d769a738be77055ec1aafbcae
