### ISSUE TITLE
Import dependencies - discussion

### ISSUE THREAD

**Issue by henrykironde** [weecology/portalr#197]
Folks, I am wondering if we need to specify the version here https://github.com/weecology/portalr/blob/master/DESCRIPTION#L44
`usethis (>= 1.4.0.9000)` or just Remotes:   r-lib/usethis will do.

I would think that `imports` would fetch the latest release.

**Comment by ha0ye** [comment]
Yup, there are features in usethis 1.5.0 that we use. Imports won't update by default unless a version is specified.
