### ISSUE TITLE
add arguments for quieting messaging if desired

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalr#198]
in particular in `download_observations` and `summarize_rodent_data` but likely others, too

**Comment by ha0ye** [comment]
Is this something you need in the functions themselves? Could you wrap the calls in `suppressMessages()` instead?

**Comment by juniperlsimonis** [comment]
"need" is a sticky word, but yes, this should be within the functions themselves. i'm aware that silencing can be forced with wraps to other functions, but the code is much much cleaner (given a logical call to the functions i'm working with) if the portalr functions can take a simple logical argument to dictate if messages are returned or not.

**Comment by ha0ye** [comment]
Ok, see if adding `quiet = TRUE` does what you want.

**Comment by juniperlsimonis** [comment]
brilliant! works like a charm, thank you!
