### ISSUE TITLE
Write yearly function

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#2]
This should accept the output of either the abundance or biomass function, which return monthly data. Options should be to summarize by year, 3-month period, or 6-month period (others?).

**Comment by skmorgane** [comment]
6 month calendar-periods and 6 month water-seasons. We've had reasons to do it either way, depending on whether seasonality is a key part of the question. Water seasons gets us closer to the actual seasonality of the system.

**Comment by gmyenni** [comment]
This overlaps with #64 , so closing this and getting more specific there.
