### ISSUE TITLE
some coloured output in `check_default_data_path` not visible in some terminal colourschemes

### ISSUE THREAD

**Issue by dill** [weecology/portalr#201]
When calling `check_default_data_path`, some output is coloured using `crayon`. The `"darkgrey"` style appears to be exactly the colour used by the solarized terminal/RStudio theme and probably also is hard to see on other "dark" terminal colourschemes. This made the output invisible until I selected the text:

![Screen Shot 2019-05-14 at 12 16 47](https://user-images.githubusercontent.com/1953/57694100-c8c84d00-7642-11e9-9266-b17b8324d4fb.png)
![Screen Shot 2019-05-14 at 12 16 58](https://user-images.githubusercontent.com/1953/57694108-cbc33d80-7642-11e9-8a47-5003195782d3.png)

Perhaps it's worth using a background to the currently dark grey text to ensure that users can tell what's going on (and that it's not a bug that there is no text there).

**Comment by ha0ye** [comment]
Thanks for the heads up, @dill. Do you have the same issue with `usethis::ui_code()`? If this is a more general issue, then we need to also file an issue in r-lib/usethis
```r
usethis::ui_code("adsf")
```

**Comment by dill** [comment]
No worries @ha0ye, the code you provide above has the same issue for me.
