### ISSUE TITLE
min_plots affects effort output when level == "plot"

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#202]
Suppose you want to extract the data for period = 394 (newmoonnumber = 420) and plot 2.

Using the default value for `min_plots = 24`, you get:
```r
> portalr::abundance(path = "repo", clean = FALSE, 
+                    level = "plot", type = "Rodents", 
+                    plots = 2, 
+                    unknowns = FALSE, shape = 'crosstab',
+                    time = "all", effort = TRUE, min_plots = 24) %>%
+     dplyr::filter(period == 394)
Loading in data version 1.109.0
  newmoonnumber period censusdate treatment plot ntraps BA DM DO DS NA OL OT PB PE PF
1           420    394 2011-05-26   control    2     NA NA NA NA NA NA NA NA NA NA NA
  PH PI PL PM PP RF RM RO SF SH SO
1 NA NA NA NA NA NA NA NA NA NA NA
```

whereas if you set `min_plots = 0`, then you get:

```r
> portalr::abundance(path = "repo", clean = FALSE, 
+                    level = "plot", type = "Rodents", 
+                    plots = 2, 
+                    unknowns = FALSE, shape = 'crosstab',
+                    time = "all", effort = TRUE, min_plots = 0) %>%
+     dplyr::filter(period == 394)
Loading in data version 1.109.0
  newmoonnumber period censusdate treatment plot ntraps BA DM DO DS NA OL OT PB PE PF
1           420    394 2011-05-26   control    2     49  0  2  1  0  0  0  0  0  0  0
  PH PI PL PM PP RF RM RO SF SH SO
1  0  0  0  0  2  0  0  0  0  0  0
```

~~The value of `ntraps` is the clue here~~ (I meant nplots, but there isn't nplots output, 🤷‍♂): only 23 plots were sampled for that census, and so the min_plots setting coerces the ntraps to be NA, even though only the abundance from a specific plot was requested, and level = "plot".

## Question
Do we want to ignore the min_plots option when level = "plot"?

**Comment by gmyenni** [comment]
@juniperlsimonis do you have thoughts about this?

**Comment by juniperlsimonis** [comment]
i would answer "yes"
it might have some cascading effects, but my guess is they'd be pretty minimal and this change makes the api and output more intuitive

**Comment by ha0ye** [comment]
> i would answer "yes"
> it might have some cascading effects, but my guess is they'd be pretty minimal and this change makes the api and output more intuitive

To be clear, "yes" == when level = "plot", ignore min_plots during the data filtering/cleaning step?

**Comment by juniperlsimonis** [comment]
correct

**Comment by ha0ye** [comment]
Actually, I think a better option is that censuses with {# of sampled plots < min_plots} could instead be filtered out and NOT be returned with level = "plot". This would add consistency in a different direction -- the periods that are returned are the same regardless of the selection of level.

I think this would also resolve the intuitive problem of seeing NAs for a plot even though it was sampled.

**Comment by juniperlsimonis** [comment]
oooh i like that.
