### ISSUE TITLE
Update for CRAN

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#203]
"Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_portalr.html>.

Please correct before 2019-06-27 to safely retain your package on CRAN."

**Comment by ha0ye** [comment]
Looks like it might be another NA issue that hashes differently on different OSes.

**Comment by ha0ye** [comment]
New plant species?
I might try and future-proof the plant tests by converting species into character instead of factor.
