### ISSUE TITLE
3 values given for current version

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalr#207]
The most recent release on the releases page is `0.2.0`. The README lists `0.2.5`. Installing from master gives `0.2.2`.

**Comment by ha0ye** [comment]
Yup, we’re behind on github releases, but are re-submitting to CRAN now, and should release soon.
I’m curious why installing from master gives 0.2.2... is it failing to install and reverting? Or did you mean CRAN?

**Comment by ethanwhite** [comment]
Oops, you're right. It's `0.2.5` from master. The `0.2.2` was from CRAN. So there should be a `0.2.2` release on GitHub that matches what's currently on CRAN right?

**Comment by ha0ye** [comment]
I think I meant to release it after it was approved by CRAN and forgot. Should we go ahead and do that now?

**Comment by ethanwhite** [comment]
Yeah, just go back and find the commit that ended up on CRAN and then release that commit as `0.2.2`. That way there's a clear link between the CRAN version and the GitHub state, which can help when running down bugs etc (which is what triggered this this morning).
