### ISSUE TITLE
R CMD check times out

### ISSUE THREAD

**Issue by jennybc** [weecology/portalr#208]
I'm about to submit an update to usethis to CRAN. portalr timed out in my automated revdep checks.

I then attempted to check it manually. At first, I saw it hang when building vignettes. I started over with `--no-build-vignettes` in both the build and check steps, but then it just hangs while running tests.

I also note that it's failing on several CRAN platforms, which is presumably related to what I'm seeing:

https://cran.r-project.org/web/checks/check_results_portalr.html

**Comment by ha0ye** [comment]
Thanks for the heads up, I knew v0.2.5 had gotten accepted, and didn't realize it had a bunch of failing checks. I'm 99% confident that the issues are related to our processing pipeline, which I am working on refactoring to improve speeds (none of these bits depend on usethis).

**Comment by jennybc** [comment]
> none of these bits depend on usethis

Thanks -- I thought so and will move forward with my release.

**Comment by ha0ye** [comment]
Seems to be related to the issues with dplyr 0.8.2, but we have refactoring complete, anyway! :sweat_smile:

**Comment by jennybc** [comment]
Interesting! I hadn't thought of that.
