### ISSUE TITLE
Latest for CRAN

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#210]
Did this get addressed in 0.2.6?

"Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_portalr.html>.

Please correct before 2019-07-14 to safely retain your package on CRAN."

**Comment by ha0ye** [comment]
Mmm, I'm not sure. I did make some changes to the code for plot-level output that also changed the hash output on the test that is failing, but I don't know if that was the source of the problem.

I'm testing on win-builder now and will let you know if that works. (after which we can upload 0.2.6 to CRAN)

**Comment by ha0ye** [comment]
Ok, I just released, and we can upload the current version to CRAN.
