### ISSUE TITLE
Crosstab quadrat-level plant data

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalr#211]
We've recently had a request for a way to easily convert the flat-format plant data into a crosstab version (i.e. not summarizing by plot, but returning quadrat-level species data).

**Comment by ha0ye** [comment]
Similar to [`summarize_individual_rodents`](https://weecology.github.io/portalr/reference/summarize_individual_rodents.html)?

**Comment by ha0ye** [comment]
I think this should fulfill the request, though the user may need an additional `tidyr::spread` to get the right columns in the crosstab.

If `shape = "crosstab"`, then the columns are for species, so to get a crosstab with columns for quadrats, use something like:
```
plant_abundance(level = "quadrat") %>% # default shape is "flat"
    tidyr::spread(quadrat, abundance)
```

**Comment by juniperlsimonis** [comment]
looks like this is accomplished now?
(just looking through issues associated with plants to see what needs to get done as i play with the plant data for the flip paper)
this works for me
```
plant_data <- summarize_plant_data(path = "repo", level = "quadrat",
                                   type = "winter-annual", correct_sp = TRUE,
                                   unknowns = FALSE, shape = "crosstab", 
                                   output = "abundance")
```

**Comment by ha0ye** [comment]
Dunno.

@skmorgane, does the current state of the package address the situation you were thinking of when creating the issue?
