### ISSUE TITLE
Allow inclusion of unsampled periods as NA in `abundance` output

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalr#213]
A lot of time-series models using NA's to indicate missing data. Having an option (or modifying `drop_na`) to allow these to be included in the output of `abundance` might be useful.

**Comment by ha0ye** [comment]
I think we could modify `na_drop` to function a bit differently when `time == "newmoon"` or `time == "date"`. This would be at least partially consistent with the meaning of `na_drop` (if you consider no sampling as insufficient sampling).

I don't think we would want to change the behavior with `time == "period"`, as there would be rows of all NAs interspersed among the observations, which seems a bit silly.

**Comment by ethanwhite** [comment]
The use case we ran into on a NEFI summer course project we're working on was that we wanted to rows of NAs when using `time = "period"` because the behavior of the state space model in JAGS (and I think several several other time-series approaches) is to treat the time-series as if it didn't have any gaps. It was only a couple of lines to fill the gaps with NA's so maybe we don't need to support it directly, but I thought it might be a semi-common need so figured I'd open an issue.

**Comment by ha0ye** [comment]
I meant that with `time = “period”`, even the time index will be NA, which makes the output unintuitive if one doesn’t know what one is looking at. With `”new moon”` or `”date”`, it’s a bit more apparent that a census should have occurred, but did not.

**Comment by ethanwhite** [comment]
Ah got it. Sorry for the confusion. Totally agree.

**Comment by ha0ye** [comment]
@juniperlsimonis Would this change to how `na_drop = FALSE` works break anything in **portalcasting**? As far as I can tell, it doesn't seem like you make any calls with that setting (`na_drop = TRUE` by default)

**Comment by juniperlsimonis** [comment]
oooo i totally agree with this. i had to do some post processing like you're mentioning, @ethanwhite, for the forecast evaluation manuscript example, as i ran those models in JAGS as well. 
as for within *portalcasting*, yeah, we only ever use the default setting, so this shouldn't impact anything, but thanks for checking!!
