### ISSUE TITLE
Heads up re: changes in usethis

### ISSUE THREAD

**Issue by jennybc** [weecology/portalr#225]
I just merged a PR from @jimhester in usethis, where we've finally managed to switch user messaging to `message()` instead of `cat()`, because we now have an attractive way to prevent such messages from being displayed in red.

Jim kindly ran revdeps and it shows you may need to tweak your tests. Jim even suggests a patch here:

https://github.com/r-lib/usethis/pull/928#issuecomment-553091603

A usethis release is probably a 4-6 weeks away.

**Comment by ha0ye** [comment]
Thanks!

FYI, @gfinak, I had to make some changes to the patterns against which the `usethis` messages were compared. Dunno if you'll need this, in addition to the suggested changes in https://github.com/r-lib/usethis/pull/928#issuecomment-553091603

 See the files changed in #226 for specifics.

**Comment by jennybc** [comment]
Note that none of us can go to CRAN with these changes until rlang does. Well, or not without effort to make things work both ways, which doesn't seem worth it in this case. I'm asking the anticipated timeline for that.

**Comment by jennybc** [comment]
I've been told an rlang patch released will be submitted to CRAN "very soon", so I think we'll all just wait for that to play out. We have quite a bit more work planned before the usethis release in any case. (It should not affect revdeps).

**Comment by gmyenni** [comment]
Update:
* A new version of usethis is ready to go to CRAN. usethis is
  currently at version 1.5.1.9000 and will become 1.6.0 upon release.

* We plan to submit usethis to CRAN on April 6.

```
== CHECK RESULTS ========================================

*   checking tests ...

     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      Actual value: ""

      ── 4. Failure: default data path functions work if unset
(@test-01-data-retrieval.R#110)  ─────────
      `m` does not match "Make sure '.Renviron' ends with a newline!".
      Actual value: ""

      ══ testthat results
══════════════════════════════════════════════════════════════════════════════
      [ OK: 193 | SKIPPED: 10 | WARNINGS: 0 | FAILED: 4 ]
      1. Failure: default data path functions work if unset
(@test-01-data-retrieval.R#107)
      2. Failure: default data path functions work if unset
(@test-01-data-retrieval.R#108)
      3. Failure: default data path functions work if unset
(@test-01-data-retrieval.R#109)
      4. Failure: default data path functions work if unset
(@test-01-data-retrieval.R#110)

      Error: testthat unit tests failed
      Execution halted

**Comment by jennybc** [comment]
Just a ping to say this is still being seen by us and, now, CRAN auto-check. But I think it will not hold up our release, since we have given plenty of advance notice.

**Comment by ha0ye** [comment]
@jennybc Thanks for the heads up. We have a PR in place once `usethis` is updated on CRAN.
