### ISSUE TITLE
Add information on how to cite portalr

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalr#237]
I just got a request for how to properly acknowledge portalr as part of the MIT attribution clause. Clearly indicating in both the DESCRIPTION and a CITATION file how things should be cited would be a good way to make our preferences for attributing use of the code.

**Comment by ha0ye** [comment]
I think the steps here are:
- [ ] clarify when to cite Zenodo vs. JOSS
- [ ] add Zenodo, JOSS, and PortalData citation to CITATION and DESCRIPTION
- [ ] include programmatic code to output the citation in raw text or .bib (optional?)
