### ISSUE TITLE
New version of tibble (CRAN)

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#239]
* A new version of tibble is ready to go to CRAN. tibble is
  currently at version 2.99.99.9014 and will become 3.0.0 upon release.

* portalr uses tibble and has problems with the new version.

* We plan to submit tibble to CRAN on Mar 18.

Major update, using vctrs internally.

I need your help to keep portalr and tibble working together smoothly.
In the next days, can you please:

1. Read about the changes to tibble at
   https://github.com/tidyverse/tibble/blob/master/NEWS.md.
   This page includes a list of breaking changes, the reasoning behind
   them, and to how to update your code.

2. Carefully inspect the failing checks listed at the bottom of this email.

3. For each failing check, either update your package, or tell me
   that I have a bug. If you have made changes to your package, please
   submit an update to CRAN before Mar 18.

If you have discovered a bug in tibble, please file an issue (ideally
with a small reprex that illustrates the problem) at
https://github.com/tidyverse/tibble/issues. If you're not sure whether
or not you've found a bug, please file an issue at
https://github.com/tidyverse/tibble/issues for discussion. Breaking
changes that are not listed qualify as bugs.

Thanks,

Kirill

== CHECK RESULTS ========================================

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      ── 3. Failure: data generated by level = 'stake' is same (ant
colony_presence_absen
      Value hashes to 2194929e3e, not 4639dbfbf3

      ── 4. Failure: data generated by level = 'plot' is same (ant
colony_presence_absenc
      Value hashes to 255aef31fb, not 60e9306bfc

      ══ testthat results
══════════════════════════════════════════════════════════════
      [ OK: 193 | SKIPPED: 10 | WARNINGS: 0 | FAILED: 4 ]
      1. Failure: data generated by default setting is same
(shrub_cover) (@test-99-regression.R#166)
      2. Failure: data generated by default setting is same (ant
colony_presence_absence) (@test-99-regression.R#177)
      3. Failure: data generated by level = 'stake' is same (ant
colony_presence_absence) (@test-99-regression.R#195)
      4. Failure: data generated by level = 'plot' is same (ant
colony_presence_absence) (@test-99-regression.R#213)

      Error: testthat unit tests failed
      Execution halted
    ```

**Comment by ha0ye** [comment]
Fascinating. There seems to be some kind of internal structuring of tibbles that affects the hash output, but which doesn't get picked up when comparing using `identical()`.

When all the columns of the tibble are selected by `dat[, seq(NCOL(dat))]`, this can also change the hash, in the same way as switching from version 2.99.99.9014 of tibble to version 3.0.0.

I think the recommended fix is to replace all the regression tests from:
```expect_known_hash(data, "**********")```
with
```expect_known_hash(data[, seq(NCOL(data)), "**********")```

which will be consistent across versions of tibble for us, and maybe futureproof against other refactoring of the internals.
