### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#249]
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_portalr.html>.

Please correct before 2020-11-27 to safely retain your package on CRAN.

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

The CRAN Team

**Comment by ha0ye** [comment]
I think we might have evaded this in the past because most of the tests that try to download data have `skip_on_cran()`.

I guess the various functions that access github, etc. should be wrapped to check for github or other access errors.

**Comment by henrykironde** [comment]
Okey based on the several resources I have read. I think they try to test every package with no internet and see how fast it would keep spinning. Usually about a few seconds as the 404 error code is sent after retrying to connect for those few seconds.

https://community.rstudio.com/t/internet-resources-should-fail-gracefully/49199

From the blogs, this seems to have people even go ahead and solve the same. 

This user has I think a better version https://community.rstudio.com/t/internet-resources-should-fail-gracefully/49199/11
So when calling any url resource, you need to cover them in some try blocks.
