### ISSUE TITLE
Remove usethis from Suggests?

### ISSUE THREAD

**Issue by jennybc** [weecology/portalr#251]
I will soon submit usethis v2.0.0 to CRAN.

I see that usethis has moved to Suggests in portalr, but no actual calls to usethis remain. I'm wondering if you might want to remove usethis from Suggests?

Selflishly, this means portalr is no longer a revdep that I have to check.

In any case, at the moment, portalr is one of the revdep failures I see, yet I don't think this has anything to do with usethis. That basically has to be true, since portalr does not call usethis, but also seems to be true from the results.

I also don't really understand why I'm seeing these failures in revdepcheck, in the cloud and locally, but CRAN isn't seeing them (yet). In any case, you probably want to take a look.

https://github.com/r-lib/usethis/blob/master/revdep/problems.md#portalr

https://gist.github.com/jennybc/12b98dc3d6ba55a6bf0a3ab1363da8ca

**Comment by ethanwhite** [comment]
I believe we are still using it, but only in once place:

https://github.com/weecology/portalr/blob/33aab477d8006129e9f05132f27c282996197982/R/download_data.R#L361-L362

Looks like the first link you send is clean again. Based on that I'd guess this is an issue we've encountered recently with heavy automated testing resulting in a the data source the package downloads rate limiting and preventing the download.

@gmyenni - Do you think this is the same thing as #249 or something else?

**Comment by jennybc** [comment]
Yes, on a second pass, portalr passed cleanly, so I've checked it off my list.

The code above forms a message. So you mention usethis but you never actually execute anything from usethis. I suspect it's still in Suggests either as a leftover (if unintentional) or as an installation aid for the user (if intentional).

The value of the gist above with my results is that it shows you a few deprecated things or warnings or incompatibilities with testthat 3. So I think it's a preview of things that will eventually need some attention. But this is entirely in your court now and there won't be any issues, I think/hope, for the usethis release.

**Comment by ethanwhite** [comment]
Ah, yeah, of course. Should have had a cup of coffee before posting that code apparently. Glad we're not getting in your way. We'll look into the deprecations.

**Comment by gmyenni** [comment]
Thanks for the heads up. I'll remove usethis from our Suggests.
