### ISSUE TITLE
shift function names to "newmoon" from "moon"

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalr#286]
I've been making a concerted effort in portalcasting to get the references to "moon" updated to be "newmoon", given that "moon" is general and the columns / data that we use are newmoons 

there is a bit of use of both names still in portal data, and portalr
for example, the column names in the moon_dates csv are newmoonnumber and newmoondate

@gmyenni do you forsee any issues with me / us updating code in portlar to match?

**Comment by gmyenni** [comment]
Sure, that should be fine. Be sure to increment the major version number when you change any columnnames or file names in PortalData. I'll send a new version to cran asap when it's ready so it won't interrupt things too much.

**Comment by gmyenni** [comment]
Closed by #288
