### ISSUE TITLE
Error in tests: zenodo 

### ISSUE THREAD

**Issue by olivroy** [weecology/portalr#298]
I couldn't figure out how to fix the 1 test failure. However, I identified the problem:

I know that it is here

```r
portal_data_path <- tempdir()
download_observations(portal_data_path, source = "zenodo", timeout = 300)
#> don't know how to convert pub_date to Date
```

Because pub_date can't be found. Maybe pub_date can be retrieved with the `modified` variable that seems to be in `contents`?

Set a break point around line 56 in R/download_data.R to debug.

It seems that the zenodo source doesn't have the same format as the other source?

I'd also be happy to send these in smaller chunks if that's better

**Comment by ethanwhite** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix portalr download bug](https://trello.com/c/Mb0sRpVm/36-fix-portalr-download-bug)
