### ISSUE TITLE
find_incomplete_censuses

### ISSUE THREAD

**Issue by emchristensen** [weecology/portalr#41]
we should check this function to make sure it's doing what we think/want it to be doing

**Comment by ha0ye** [comment]
It looks like it identifies all periods (after period == 26) where at least one of the plots was *not* sampled (sampled == 0).

Can you elaborate on what you are worried about?

**Comment by ha0ye** [comment]
Ok, looks like this is fine in terms of marking incomplete censuses (other than the initial ones where plot 24 did not exist). @emchristensen can re-open or create a new issue if there's something to be fixed.
