### ISSUE TITLE
Standardizing abundances according to how many plots were trapped

### ISSUE THREAD

**Issue by diazrenata** [weecology/portalr#47]
I was trying to use portalr to summarize rodent abundances by treatment, correcting for how many plots were trapped for each treatment in each period. It was a little complicated extracting all of this information as a single table. 

I set up a function based on the abundances() function in portalr to report abundance per plot trapped per treatment. It's the file RodentAbundancesAdjustable.R in the diazrenata/portalr repository. I tried to make it compatible with the portalr functions, so it might be useful as a starting point for incorporating this in the package?

(There's also code to take that a step forward and report abundance per plot trapped, multiplied the number of plots that are 'usually' trapped for that treatment, but I'm not confident that my way of defining 'usual' is something you'd want baked in.)

**Comment by gmyenni** [comment]
Can you include this in the abundance function as an argument (an option to either use actual abundance, or adjusted abundance)?

**Comment by diazrenata** [comment]
I updated the RodentAbundancesAdjustable.r file in my fork to allow an argument "adj" to specify whether to report raw abundances or the abundance/plot trapped. It only applies to summary by site or by treatment.

There is code to guess the "usual" number of plots trapped (approx. mode of how many plots are trapped per treatment) and multiply by that. I'm leaving that commented out for now because it involves judgement calls and could be confusing.

I think RodentAbundancesAdjustable.r could replace RodentAbundances.R, but I don't want to mess with the package....

**Comment by gmyenni** [comment]
I think you should go ahead and add that section (your `if (adj == T) { . . .` section) to RodentAbundances.R itself and submit a PR. And keep the correction for usual number of plots trapped. We can have a discussion in a Portal logistics meeting about the best way to do that, and update it according to what we decide then.

**Comment by diazrenata** [comment]
I wrote the adjustment into the RodentAbundances file. I think we should talk about how to really integrate the adjustment. Right now, if you ask it to adjust, it will still tell you the raw number, the number of plots trapped, and the adjusted number. I think this is important because the automatic way of determining the "usual" number of plots could make it very confusing without having the intermediate steps visible to the user. 
So right now, adjusting will give you a table that is a different shape from the non-adjusted table. I think we could change that so it looks more streamlined, but we'd need to make it very clear to the user what that was doing...

**Comment by ethanwhite** [comment]
> So right now, adjusting will give you a table that is a different shape from the non-adjusted table.

Generally speaking, it's considered good practice to have functions return similar types and structures of objects regardless of the specific arguments passed to them. This allows people using the function to not understand the potential consequences of every optional parameter to use the function. In this case that would mean not returning a table that has a different shape.

My general approach to something like this would be to:

1. Set the default to the option that people should use most of the time
2. Clearly document the behavior in the function documentation
3. If there real concern about regularly accidental misuse or confusion, consider adding a warning message that prints when the code is run with the option in question (e.g., if you create a histogram in `ggplot` without setting the `bins` argument it will tell you that it used 30 bins and that this might not be the best choice).

If there is sufficient concern about misuse the use of adjustments could be made in a separate function, but the trade off is a combination of duplicate code and the fact that most users won't use this extra function and therefore might be more likely to accidentally not correct for missed sampling.

**Comment by gmyenni** [comment]
Include column to indicate number of traps set by period/plot/treatment.

**Comment by DAPPERstats** [comment]
I've had a chance to dig into the functions and here's what I'm proposing (and starting to work on implementing) to do with the `get_rodent_data` function to address the sample effort issue here as well as the completeness issue in #88.

1. for each level (plot, treatment, site), we provide additional column(s) with the current data table that include the total number of units sampled at the lower levels (traps within plots, plots within treatments/site).
 
   - putting in "plot" for level would get the current table with a column of how many traps were set within that plot

   - putting in "treatment" would get the current table with a column of how many plots were in that treatment and a column of how many traps were set within that treatment (across all plots)

   - putting in "site" would get the current table with a column for the total number of plots and the total number of traps (across all plots).

   - the data are already there in the trapping data table, so we just need to tack them on accordingly

2. we include a set of flexible arguments for how to handle the incomplete data at the relevant level

   - there is currently a single logical `incomplete` argument in `get_rodent_data` that is passed directly down to `clean_rodent_data` and `join_trapping_to_rodents`. this appears to be a large part of what's hamstringing our ability to generate different versions of the data. 

   - I think what we need to do is get the full data set (use `incomplete = TRUE` in `clean_rodent_data` and `join_trapping_to_rodents`) regardless of the inputs at the `get_rodent_data` level and then have a set of inputs at the `get_rodent_data` level to dictate how we manage summarizing the data

   - this does produce a larger data set, but (as of now) it's a 5.1% increase (63433 vs 60347 rows), so not a massively larger data structure. 

   - by simply grabbing all of the data, the edits to address these issues can be confined to the `get_rodent_data` function, and the `clean_rodent_data` and `join_trapping_to_rodents` functions can be left as is.  

   - this will help us avoid the hard binary of a single logical argument for the data cleaning, thereby allowing us to flexibly produce multiple (> 2) different versions of the data for each level. 

    - for example, at the plot level, someone might want [1] all plots for all moons, [2] only plots when there was at least some non-0 effort, [3] only plots where there was full effort (49 traps), [4] only plots where there was full site effort (24 plots, each with 49 traps); and they might want all of the potential observations where there was insufficient effort to be included as NAs or to be dropped from the data. 

   - a similar (but not identical) set of outputs are of potential interest for treatment and site level data. 

   - my current thoughts on the input arguments are: [1] the within-plot effort required for a plot to be included (1 - 49, default to 49), [2] the site-level effort required for a plot to be included (1 - 24, default to 24), and [3] if NAs should be retained or dropped (logical, default to retained).

I have a branch open where I'm starting to work on this stuff, let me know if you all have specific suggestions, feedback, etc.

**Comment by DAPPERstats** [comment]
@ethanwhite @skmorgane

**Comment by ethanwhite** [comment]
This plan sounds reasonable to me and my previous concern about different table shapes is moot given the need for different levels results in changes in the columns anyway.

**Comment by gmyenni** [comment]
Closed via #114
