### ISSUE TITLE
Plant data summaries

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#6]
We still need matching functions to summarize the plant data similarly to the rodent data:

- Abundance by plot, treatment, or site

- summarized by month, 3-months, 6-months, or year

**Comment by gmyenni** [comment]
How to incorporate species ID fixes:
options in arguments, or produce two columns (raw codes and 'fixed' codes)

**Comment by ha0ye** [comment]
I like having the option in an argument, but have the output column have a different name (e.g. 'raw_species_code', 'fixed_species_code')

**Comment by gmyenni** [comment]
Species filtering 
* just annuals
* all species (including shrubs)

**Comment by emchristensen** [comment]
Portal_plot_treatments.csv indicates annuals were removed on some plots 1985-1987. However there is still annual data recorded for those plots in those years. 
Options:
- remove this data, I'm not even sure what it means
- include option to summarize and return this data anyway, with a warning or flag to indicate weirdness

**Comment by ha0ye** [comment]
> include option to summarize and return this data anyway, with a warning or flag to indicate weirdness

Maybe exclude it as a default, but have the option to include it, as in `remove_incomplete_censuses`?

**Comment by emchristensen** [comment]
[I'm also throwing some issues up in PortalData about the plant data, mostly ways to reorganize the supplementary tables to make summarizing plant data easier for me]

**Comment by gmyenni** [comment]
I don't think plants were removed from the actual quadrats. @skmorgane ?

**Comment by skmorgane** [comment]
I can't find anything that says one way or another. The 1998 chapter is unclear on this. I don't think they ever published anything about that manipulation, either. I assume they did not touch the quadrats, but there are notes about this experiment in the archive. It may be worth trying to dig those up.

**Comment by skmorgane** [comment]
The note I remember was from the grad student to Jim explaining that when he censused the plants on those plots the plants not killed by the Roundup were really big. Maybe there's language in that note that makes it clear if they sprayed the quadrats too or if the islands of untouched plants in the quadrats just got big? We can also email Jim.

**Comment by emchristensen** [comment]
I'm working on this on a branch called plant_summaries off of my fork of portalr (I don't know, just go with it).  Basically I created a script called PlantData.R which ~= RodentData.R and plant_data_processing.R ~= data_processing.R

So far it works (!) to summarize plant quadrat abundance by plot, treatment, or site level; you can specify all species, annuals only, or non-woody (exclude shrubs); you can get all plots or longterm only; you can get unknowns or not. 

I have not created any tests yet.  But at this point anyone is welcome to chime in with needs/suggestions

**Comment by ha0ye** [comment]
@emchristensen I think you can go ahead and submit a PR now, and later commits that add tests will get included automatically in that PR (if it hasn't been merged yet).

LMK if you need help with tests, but I think it shouldn't be too bad to copy-paste the existing tests and just change some of the specific values. You should be able to test-run the tests using `devtools::test()` or the RStudio keyboard shortcut (ctrl-shift-t).

**Comment by emchristensen** [comment]
@ha0ye I'm having test problems. I needed to add a few columns to Portal_plant_census_dates.csv in order to make my summarizing functions. But the way tests are set up right now they only test on the latest release -- so no matter what my tests will fail because that column is not in the release version.  So this has become a slightly larger question: can/should we test on non-release data?  I realize non-release may be less stable, but it's also the only way I can write tests for the plant functions I made.

**Comment by ha0ye** [comment]
@emchristensen I think the way I would approach this is to include a line in your test file that downloads the non-release data:
```
download_observations(".", release_only = FALSE)
```
And as long as this is the last test that is run, it won't affect the other tests, since those tests download  and use the release version of the data. If this turns into a problem, we can play around with using a temporary directory, but let's try this simple fix first.

**Comment by emchristensen** [comment]
I could also have the plant tests pull data directly from the repo.  the tests pass that way.

**Comment by ha0ye** [comment]
Is this using the `path = "repo"` option? I think we discussed updating the code so that this would also grab the release version by default, so I think sticking to using `download_observations` is worthwhile future-proofing here.

**Comment by emchristensen** [comment]
the tests are now passing.  ready for review...

**Comment by ha0ye** [comment]
I think there some duplication in the functions in `R/plant_data_processing.R` and `R/data_processing.R`. Can you merge these all into `R/data_processing.R`?

We can decide later if some of the functions should be merged, but this will prevent confusion from having the same function defined (identically) in separate locations.

**Comment by emchristensen** [comment]
done.

**Comment by ha0ye** [comment]
closed by #95
