### ISSUE TITLE
Update regression test

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#66]
Currently checks regression results against a pre-computed result, but changes with new data.
Maybe fix by restricting test to run regression over a preset time period?
  
Hmm, the test does seem to restrict time periods already...

**Comment by gmyenni** [comment]
#76 resolves the current issue, but I'll leave this open for a possible long-term fix.

**Comment by gmyenni** [comment]
Actually, testing with the latest release should solve this.
