### ISSUE TITLE
Add contributions.md

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#67]
Write up for the lab:
- [x] workflow instructions (Git branching)

Inclusion into `contributions.md` file:
- [x] documentation (Roxygen)
- [x] testing (testthat)
- [x] building (devtools)

**Comment by ha0ye** [comment]
Should we modify a version of the lab Code of Conduct for contributors? We could also adopt one of the commonly used ones for software projects elsewhere.

**Comment by ethanwhite** [comment]
We typically use an adapted version of the Contributor Covenant:

* https://github.com/weecology/retriever/blob/master/docs/code_of_conduct.rst
* https://github.com/weecology/retriever/blob/master/docs/code_of_conduct.rst

I'd suggest we adopt this as the lab standard and make it standard to include them in repos that represent meaningful software packages.
