### ISSUE TITLE
Improve get data options

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#69]
esp. download location

**Comment by ha0ye** [comment]
`download_observations` now gets the latest release from PortalData repo by default.
If there's nothing else, then I think this is resolved by PR #77

**Comment by gmyenni** [comment]
Does `observations_are_new` get used anywhere anymore? Did we just lose track of that at some point?

**Comment by ha0ye** [comment]
I use it in the vignette, but it's not used in portalr or portalPredictions...

**Comment by ha0ye** [comment]
[per discussion with @gmyenni, @emchristensen, @sdtaylor]
`load_data` functionality should be expanded:
* if repo (get data from repo)
* if download (use `download_observations`)

**Comment by ha0ye** [comment]
Somehow check for release version and/or newer copy of local data.
