### ISSUE TITLE
NDVI function

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#70]
monthly, seasonal summary options, linked to newmoonnumber

**Comment by ha0ye** [comment]
see also https://github.com/weecology/PortalData/issues/164

**Comment by DAPPERstats** [comment]
I've pulled the NDVI summarizing out into its own function as part of PR https://github.com/weecology/portalr/pull/108

I know it'll cause downstream breaks in portal predictions, and I will follow these updates through to the end of the code in that repo. Let me know if I need to update dependencies anywhere else.

**Comment by gmyenni** [comment]
Closed via #108
