### ISSUE TITLE
Hex sticker for the package

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalr#78]
as suggested by @sdtaylor, see e.g. https://www.tidyverse.org/packages/

**Comment by DAPPERstats** [comment]
totally think this is a good idea
check out http://hexb.in/ for specifics of the design
do we have anyone in the lab who is good at design?/would want to take this up? if not, this is totally something we could hire someone to do for a pretty minimal price and get a really pretty logo. (my design person charges ~$800 for a logo)

**Comment by ha0ye** [comment]
I think there was a designer used for some of the rodent profile images (before they were all replaced with photos). I can do some design ([example](https://github.com/maxogden/hexbin/blob/gh-pages/hexagons/SIO_ODS.png)), but have limited illustration skills, so would need something to work off of.

What are we thinking? An octocat-shaped portal, from which kangaroo rats spill forth?

**Comment by bleds22e** [comment]
It would be cool to have a kangaroo rat emerging from some type of portal , like the video game


Ellen K. Bledsoe

Ph.D. Student, Interdisciplinary Ecology

School of Natural Resources and Environment

Dept. of Wildlife Ecology and Conservation

University of Florida

ellen.bledsoe@ufl.edu

________________________________

**Comment by gmyenni** [comment]
Done by @bleds22e !
