### ISSUE TITLE
DataSummaries - figure out how to obtain most recent data package version of the portal data

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalr#9]

**Comment by skmorgane** [comment]
I don't exactly remember what this issue was created for. Here's my memory: we currently pull from the repo, but not the data package, but we'd prefer if the default was the data package because it is the more vetted version of the data. People should actively have to choose the repo (and the errors it contains in the newest data).  This seems like something we need to figure out before we release Portalr.

**Comment by ha0ye** [comment]
@skmorgane By "data package", do you mean downloading the "portal-dev" dataset using retriever (https://github.com/weecology/retriever)?

**Comment by ha0ye** [comment]
Portal Forecasting should pass an argument to portalr to get the raw data, whereas the default option should be the "official release"

**Comment by ha0ye** [comment]
This is now subsumed into issue #69, and is closed by PR #77
