### ISSUE TITLE
Do we need to name columns in load_data function?

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalr#94]
Right now, adding new columns in PortalData means load_data will fail when release_only=FALSE.

Can we find another way to QC the columns without naming them manually?

**Comment by ha0ye** [comment]
Yeah, we can do a check for the existence of the "renamed" column and then use dplyr::rename to be agnostic to the order of the columns.

**Comment by ha0ye** [comment]
Actually, other than changing `speciescode` to `species` in the `species_table`, it looks like the other renaming is redundant with both current and release versions of PortalData...

**Comment by ha0ye** [comment]
I think some of the later functions expect specific names (perhaps for consistency?)
The changes I added to #90 check for the old column names and rename them accordingly, so they should work even if the order of columns is changed or if the raw data tables have "fixed" column names.

**Comment by gmyenni** [comment]
Okay, yeah, #90 looks much better. Thanks!
